/** DrawingML ST_PositiveFixedPercentage values are limited to 0–100%. */
export const POSITIVE_FIXED_PERCENT = new Set([
	'alpha',
	'tint',
	'shade',
	'sat',
	'lum',
	'red',
	'green',
	'blue',
]);

/**
 * DrawingML ST_PositivePercentage values have a lower bound of zero but no
 * 100% upper bound. Office themes commonly use modulation values above 100%.
 */
export const POSITIVE_PERCENT = new Set([
	'alphaMod',
	'satMod',
	'lumMod',
	'redMod',
	'greenMod',
	'blueMod',
	'hueMod',
]);

export const FIXED_PERCENT = new Set([
	'alphaOff',
	'satOff',
	'lumOff',
	'redOff',
	'greenOff',
	'blueOff',
]);

export const ENUMS: Record<string, readonly string[]> = {
	'ph@type': [
		'title',
		'body',
		'ctrTitle',
		'subTitle',
		'dt',
		'sldNum',
		'ftr',
		'hdr',
		'obj',
		'chart',
		'tbl',
		'clipArt',
		'dgm',
		'media',
		'sldImg',
		'pic',
	],
	'sldLayout@type': [
		'title',
		'tx',
		'twoColTx',
		'tbl',
		'txAndChart',
		'chartAndTx',
		'dgm',
		'chart',
		'txAndClipArt',
		'clipArtAndTx',
		'titleOnly',
		'blank',
		'txAndObj',
		'objAndTx',
		'objOnly',
		'obj',
		'txAndMedia',
		'mediaAndTx',
		'objOverTx',
		'txOverObj',
		'txAndTwoObj',
		'twoObjAndTx',
		'twoObjOverTx',
		'fourObj',
		'vertTx',
		'clipArtAndVertTx',
		'vertTitleAndTx',
		'vertTitleAndTxOverChart',
		'twoObj',
		'objAndTwoObj',
		'twoObjAndObj',
		'cust',
		'secHead',
		'twoTxTwoObj',
		'objTx',
		'picTx',
	],
	'pPr@algn': ['l', 'ctr', 'r', 'just', 'justLow', 'dist', 'thaiDist'],
	'bodyPr@anchor': ['t', 'ctr', 'b', 'just', 'dist'],
	'schemeClr@val': [
		'bg1',
		'tx1',
		'bg2',
		'tx2',
		'accent1',
		'accent2',
		'accent3',
		'accent4',
		'accent5',
		'accent6',
		'hlink',
		'folHlink',
		'phClr',
		'dk1',
		'lt1',
		'dk2',
		'lt2',
	],
	'ln@cap': ['rnd', 'sq', 'flat'],
	'ln@cmpd': ['sng', 'dbl', 'thickThin', 'thinThick', 'tri'],
	'prstDash@val': [
		'solid',
		'dot',
		'dash',
		'lgDash',
		'dashDot',
		'lgDashDot',
		'lgDashDotDot',
		'sysDash',
		'sysDot',
		'sysDashDot',
		'sysDashDotDot',
	],
};

export const BLACK_WHITE = [
	'clr',
	'auto',
	'gray',
	'ltGray',
	'invGray',
	'grayWhite',
	'blackGray',
	'blackWhite',
	'black',
	'white',
	'hidden',
];
